config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'welcome/index'

  resources :reviews
  resources :categories
  resources :articles 
  root 'welcome#index'
  #get 'categories/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  #create, Read, Update, Destroy
=begin
    
    :create = new, create
    :read = index, show
    :update = edit,update
    :destroy = destroy
    :manage = new, create, index, show, esit, update, destroy
       
  
=end

  def initialize(user)
    if user.nil?
        can :read, [Category, Article]
    elsif user.role? "admin"
    # user.roles.pluck(:name).include? "admin"
        can :manage, [Category,Article,Review]

    elsif user.role? "moderator"
        can :read, [Category,Article,Review]
        can :create, Review
        can :update, [Category, Article]
        can :destroy, Review
    
    elsif user.role? "customer"
    # user.roles.pluck(:name).include? "customer"

        can :read, [Category,Article]
        can [:read, :create], Review 
        can [:update, :destroy], Review do |review|
            review.user_id == user.id
        end

    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  mount_uploader :feature_image_url, CoverUploader

  extend FriendlyId
  friendly_id :title,  use: [:slugged, :finders]
  has_many :reviews

  belongs_to :category
	validates_presence_of :title,:body,:category_id,:publish_date,:feature_image_url
	validate :publish_date_cannot_be_more_than_30_days
  validates_length_of :title, minimum: 5
  validates_length_of :body, minimum: 5
	#validate :publish_date_less_than_present_date

    
 
  	def publish_date_cannot_be_more_than_30_days
    	if publish_date.present? && publish_date > Date.today.next_month
      		errors.add(:publish_date, "Publish date should be within 30 days from the present date")
    	end
  	end

  	#def publish_date_less_than_present_date
  	#	if publish_date < Date.today
  	#		is_published :enabled 

  	#	end
  	#end



end

app/models/category.rb
class Category < ApplicationRecord
	has_many :articles
	validates_presence_of :name,:description
end

app/models/permission.rb
class Permission < ApplicationRecord
	belongs_to :user
	belongs_to :role
	
end

app/models/review.rb
class Review < ApplicationRecord

	belongs_to :article
	belongs_to :user

	validates_presence_of :body,:article_id,:user_id
	validates_length_of :body, within: 10...1000
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :permissions
	has_many :users, through: :permissions

	validates_presence_of :name
	validates_uniqueness_of :name

end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  
  has_many :permissions
  has_many :roles, through: :permissions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :username, :mobile
  validates_numericality_of :mobile
  validates_length_of :mobile, is: 10

  #callback
  after_create :assign_customer_role

  def assign_customer_role
  	#binding.pry
  	Permission.create(user_id: self.id, role_id: Role.second.id)
  end 

  def role?(role)
  	self.roles.pluck(:name).include?(role)
  end                       	


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	rescue_from CanCan::AccessDenied do
		redirect_to root_path, notice: "The page you are looking for doesn't exist"
	end


	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :mobile])
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_user!, except: [:index,:show]
	#load_and_authorize_resource
	load_and_authorize_resource :find_by => :slug
	def index
		@article = Article.all
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		if @article.save
			redirect_to articles_path
		else
			render action: 'new'
		end
	end

	def show
		@article = Article.friendly.find(params[:id])
		@review = Review.new
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		if @article.update_attributes(article_params)
			redirect_to article_path, notice: "Successfully updated"
			
		else
			render action: 'edit'
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to articles_path
	end

	private
	def article_params
		params[:article].permit(:title,:body,:category_id,:publish_date,:feature_image_url,:is_published, :slug)
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	load_and_authorize_resource #invokes ability class

	def index
		@category = Category.all
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			redirect_to categories_path
		else
			render action: 'new'
		end

	end

	def show
		@category = Category.find(params[:id])
		@articles = @category.articles
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])
		if @category.update_attributes(category_params)
			redirect_to categories_path
			
		else
			render action: 'edit'
		end
	end

	def destroy
		@category = Category.find(params[:id])
		@category.destroy
		redirect_to categories_path
	end

	
	private

	def category_params
		params[:category].permit(:name,:description)
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	def create
		#binding.pry
		@review = Review.new(review_params)
		@review.user_id = current_user.id
		#binding.pry
		if @review.save
			#binding.pry
			redirect_to article_path(@review.article), notice: "Thank you for adding comments"
		else
			redirect_to article_path(@review.article), notice: "not save"
		end
	end

	def destroy
		@review = Review.find(params[:id])
		@review.destroy
		redirect_to article_path(@review.article_id)
	end

	private

	def review_params
		params[:review].permit(:body,:article_id)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |a| %>
	
	<% if @article.errors.any? %>
		
		<ul>
			<% @article.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>

		
	<% end %>

	<label for="article_category_id">Category ID</label><br>
	<%= a.collection_select :category_id,Category.all, :id, :name,prompt: "Select Category" %> <br><br>

	<label for="article_title">Title : </label><br>
	<%= a.text_field :title %> <span id="titleHandleMsg"></span><br>

	<label for="article_body">Enter your blog here : </label><br>
	<%= a.text_area :body %><br>

	
	<label for="article_published_date">Article Published Date :</label><br>
	<%= a.date_select :publish_date %><br><br>

	<%= a.check_box :is_published %> <label for="is_published">is published</label><br><br>

	<label for="article_image_url">Image URL : </label><br>
	<%= a.file_field :feature_image_url %><br>


	<%= a.submit %>
<% end %> 
<script type="text/javascript">
	nameHandle = document.getElementById("article_title")
	titleHandleMsg = document.getElementById("titleHandleMsg")
	nameHandle.addEventListener('focus',function(){
		titleHandleMsg.innerHTML = "Enter the product name";
	},false)
	nameHandle.addEventListener('blur',function(){
		if (nameHandle.value == "") {
			titleHandleMsg.innerHTML = "Name can't be empty";	
		}
		else{
			titleHandleMsg.innerHTML = "";
		}
		
	},false)

</script>

app/views/articles/edit.html.erb
<h2>Edit Article</h2>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Article Details (Total - <%= @article.count %>)</h1>

<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>

<table border="4">
	<tr>
		<th>Title</th><th>Description</th><th>Category</th>
	</tr>
	<% @article.each do |a| %>
	
		<tr>
			<td><%= a.title %></td>
			<td><%= a.body %></td>
			<td><%= link_to "view",a %></td>
		</tr>
	
	<% end %>
</table>
<% if (user_signed_in?) && (can? :create, Article.new) %>
	<br><b><%= link_to "Add Article",new_article_path %></b>
<% end %> 

app/views/articles/new.html.erb
<h2>Add Article</h2>
<%= render 'form' %>

app/views/articles/show.html.erb
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>

<center>
	<table border="1">
		<tr>
			<th>Title</th>
			<th>Body</th>
			<th>Category</th>
			<th>Publish Date</th>
			<th>Published</th>
			<th>Image</th>

		</tr>
		<tr>
			<td><%= @article.title %></td>
			<td><%= @article.body %></td>
			<td><%= Category.find(@article.category_id).name %></td>
			<td><%= @article.publish_date %></td>
			<td><%= @article.is_published %></td>
			<td><%= image_tag(@article.feature_image_url.url, size: "50*50") %></td>
			<% if (user_signed_in?) && (can? :update, @article) %>
				<td><b><%= link_to "Edit Article",edit_article_path(@article.id) %></b></td>
				<td><b><%= link_to "Delete",article_path(@article.id),method: :delete,data: {confirm: "Are you sure ?"} %></b></td> 
			<% end %>

		</tr>

	</table>

	<% if @article.reviews.empty? %>
		<p>No reviews found. Be the first one to review . </p>
	<% else %>
		<h3>Listing Reviews</h3>
		<ol>
			<% @article.reviews.each do |review| %>
				<li><b><%= review.user.username  %></b> - <%= review.body %>
				<% if (user_signed_in?) && (can? :update, review) %>
					
					<%= link_to "destroy", review_path(review.id), method: :delete, data: {confirm: "Are you sure?"} %>

				</li>
				<% end %>
			
			<% end %>

		
	<% end %>

	<%= form_for (@review) do |f| %>
		<label for="review_body"></label>
		<%= f.text_area :body %> <br>

		<%= f.hidden_field :article_id, value: @article.id %>
		<br>

		<%= f.submit "Add review" %>
	<% end %>

</center>

app/views/categories/_form.html.erb
<%= form_for @category do |c| %>
	<% if @category.errors.any? %>
		
		<% @category.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
 		
	<% end %>
	<br>
	<label for="category_name">Category Name : </label><br>
	<%= c.text_field :name %><br>

	<label for="category_desc">Description : </label><br>
	<%= c.text_area :description %><br>

	<%= c.submit %>
<% end %>

app/views/categories/edit.html.erb
<h2>Edit Category</h2>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1>Category Details (Total - <%= @category.length %>)</h1>

<% @category.each do |c| %>
	<p><b><%= c.name %> (<%= c.articles.length %>)</b> - <%= link_to "show details",category_path(c.id) %>
	
	<hr>
<% end %>
<% if (user_signed_in?) && (can? :create, Category.new) %>
	<br><b><%= link_to "Add Category",new_category_path %></b>
<% end %> 

app/views/categories/new.html.erb
<h1>Add Category</h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<center>
	<table border="1">
		<tr><td><center><h2>Name : <%= @category.name %></h2></center></td></tr>
		<tr><td><h4>Description : <%= @category.description %></h4></td></tr>

		<tr>
			<td><h4>Article Title :
				<ul> 
					<% @articles.each do |a| %>
						<li><%= a.title %></li>
					<% end %>
 				</ul>

					</h4></td></tr>
		<tr>
		<% if (user_signed_in?) && (can? :update,@category) %>
			<td><b><%= link_to "Edit",edit_category_path(@category.id) %></b>
			<b><%= link_to "Delete",category_path(@category.id),method: :delete,data: {confirm: "Are you sure ?"} %></b> </p></td>
		<% end %> 	
		</tr>
	</table>



</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to "Accout Setting",edit_user_registration_path %> | <%= link_to "Log out",destroy_user_session_path,method: :delete %>            
      <br><b>Welcome <%= current_user.username %></b>

      
    <% else %>  
      <%= link_to "Register",new_user_registration_path %> | 
      <%= link_to "Sing in",new_user_session_path %> |
    <% end %>

    <hr>
    <%= link_to "Category",categories_path %> | <%= link_to "Article",articles_path %>
    <br>
    <%= notice %>
    <%= yield %>
    <%= alert %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to our Blog Application</h1>
<p>Here you can write your own article....</p>